server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smdka/maxim_config
          search-paths:
            - riders
            - eureka-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/